-- begin DEMO_SUBSCRIPTION
alter table DEMO_SUBSCRIPTION add constraint FK_DEMO_SUBSCRIPTION_ON_CUSTOMER foreign key (CUSTOMER_ID) references DEMO_CUSTOMER(ID)^
create index IDX_DEMO_SUBSCRIPTION_ON_CUSTOMER on DEMO_SUBSCRIPTION (CUSTOMER_ID)^
-- end DEMO_SUBSCRIPTION
