-- begin YETDEMO_SUBSCRIPTION
alter table YETDEMO_SUBSCRIPTION add constraint FK_YETDEMO_SUBSCRIPTION_ON_CUSTOMER foreign key (CUSTOMER_ID) references YETDEMO_CUSTOMER(ID)^
create index IDX_YETDEMO_SUBSCRIPTION_ON_CUSTOMER on YETDEMO_SUBSCRIPTION (CUSTOMER_ID)^
-- end YETDEMO_SUBSCRIPTION
