alter table YETDEMO_SUBSCRIPTION add constraint FK_YETDEMO_SUBSCRIPTION_CUSTOMER foreign key (CUSTOMER_ID) references YETDEMO_CUSTOMER(ID);
create index IDX_YETDEMO_SUBSCRIPTION_CUSTOMER on YETDEMO_SUBSCRIPTION (CUSTOMER_ID);
